from config.dependencies import get_current_user

print(get_current_user(credentials="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGY5ZGFkZDdlMjY5ODVkYjdlMDM1ZDkiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMjY5NDI3fQ.eCUYoY9K_b2zfKHMx7h2lNkvVgPrYSJ8bsUGRKOD5bs"))