# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(100, 50, 71, 16))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 10, 131, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(200, 50, 113, 21))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(200, 90, 113, 21))
        self.password.setObjectName("password")
        self.image_path = QtWidgets.QLineEdit(Dialog)
        self.image_path.setGeometry(QtCore.QRect(200, 130, 113, 21))
        self.image_path.setObjectName("image_path")
        self.OK_Button = QtWidgets.QPushButton(Dialog)
        self.OK_Button.setGeometry(QtCore.QRect(90, 210, 113, 32))
        self.OK_Button.setObjectName("OK_Button")
        self.Cancel_Button = QtWidgets.QPushButton(Dialog)
        self.Cancel_Button.setGeometry(QtCore.QRect(210, 210, 113, 32))
        self.Cancel_Button.setObjectName("Cancel_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_1.setText(_translate("Dialog", "Username:"))
        self.label_2.setText(_translate("Dialog", "Password:"))
        self.label_3.setText(_translate("Dialog", "Image path:"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Thêm ảnh cho user</p></body></html>"))
        self.OK_Button.setText(_translate("Dialog", "OK"))
        self.Cancel_Button.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
