# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 360)
        Dialog.setMinimumSize(QtCore.QSize(640, 360))
        Dialog.setMaximumSize(QtCore.QSize(640, 460))
        self.videoLabel = QtWidgets.QLabel(Dialog)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 640, 360))
        self.videoLabel.setMinimumSize(QtCore.QSize(640, 360))
        self.videoLabel.setMaximumSize(QtCore.QSize(640, 360))
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.videoLabel.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
