# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 430)
        MainWindow.setMinimumSize(QtCore.QSize(550, 430))
        MainWindow.setMaximumSize(QtCore.QSize(550, 430))
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.get_users_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_users_button.setGeometry(QtCore.QRect(20, 20, 120, 50))
        self.get_users_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #3498db; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.get_users_button.setIconSize(QtCore.QSize(16, 16))
        self.get_users_button.setAutoDefault(False)
        self.get_users_button.setObjectName("get_users_button")
        self.add_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_user_button.setGeometry(QtCore.QRect(20, 90, 120, 50))
        self.add_user_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #3498db; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.add_user_button.setIconSize(QtCore.QSize(16, 16))
        self.add_user_button.setAutoDefault(False)
        self.add_user_button.setObjectName("add_user_button")
        self.delete_user_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_user_button.setGeometry(QtCore.QRect(20, 300, 120, 50))
        self.delete_user_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #3498db; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.delete_user_button.setIconSize(QtCore.QSize(16, 16))
        self.delete_user_button.setAutoDefault(False)
        self.delete_user_button.setObjectName("delete_user_button")
        self.add_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_image_button.setGeometry(QtCore.QRect(20, 160, 120, 50))
        self.add_image_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #3498db; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.add_image_button.setIconSize(QtCore.QSize(16, 16))
        self.add_image_button.setAutoDefault(False)
        self.add_image_button.setObjectName("add_image_button")
        self.delete_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_image_button.setGeometry(QtCore.QRect(20, 230, 120, 50))
        self.delete_image_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #3498db; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.delete_image_button.setIconSize(QtCore.QSize(16, 16))
        self.delete_image_button.setAutoDefault(False)
        self.delete_image_button.setObjectName("delete_image_button")
        self.add_camera_manager_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_camera_manager_button.setGeometry(QtCore.QRect(160, 20, 161, 50))
        self.add_camera_manager_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #27ae60; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e8449; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2ecc71; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.add_camera_manager_button.setIconSize(QtCore.QSize(16, 16))
        self.add_camera_manager_button.setAutoDefault(False)
        self.add_camera_manager_button.setObjectName("add_camera_manager_button")
        self.delete_camera_manager_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_camera_manager_button.setGeometry(QtCore.QRect(160, 90, 161, 50))
        self.delete_camera_manager_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #27ae60; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e8449; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2ecc71; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.delete_camera_manager_button.setIconSize(QtCore.QSize(16, 16))
        self.delete_camera_manager_button.setAutoDefault(False)
        self.delete_camera_manager_button.setObjectName("delete_camera_manager_button")
        self.delete_camera_info_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_camera_info_button.setGeometry(QtCore.QRect(160, 160, 161, 50))
        self.delete_camera_info_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #27ae60; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e8449; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2ecc71; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.delete_camera_info_button.setIconSize(QtCore.QSize(16, 16))
        self.delete_camera_info_button.setAutoDefault(False)
        self.delete_camera_info_button.setObjectName("delete_camera_info_button")
        self.get_emotion_summary_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_emotion_summary_button.setGeometry(QtCore.QRect(160, 230, 161, 50))
        self.get_emotion_summary_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #27ae60; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e8449; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2ecc71; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.get_emotion_summary_button.setIconSize(QtCore.QSize(16, 16))
        self.get_emotion_summary_button.setAutoDefault(False)
        self.get_emotion_summary_button.setObjectName("get_emotion_summary_button")
        self.get_tracking_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_tracking_data_button.setGeometry(QtCore.QRect(160, 300, 161, 50))
        self.get_tracking_data_button.setStyleSheet("QPushButton {\n"
"    border-radius: 10px; /* Bo góc với bán kính 15 pixel */\n"
"    background-color: #27ae60; /* Màu nền */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e8449; /* Đường viền */\n"
"    font: 14pt \".AppleSystemUIFont\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2ecc71; /* Màu nền khi trỏ chuột vào nút */\n"
"}\n"
"")
        self.get_tracking_data_button.setIconSize(QtCore.QSize(16, 16))
        self.get_tracking_data_button.setAutoDefault(False)
        self.get_tracking_data_button.setObjectName("get_tracking_data_button")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 20, 161, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.cameraInput.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraInput.setObjectName("cameraInput")
        self.verticalLayout.addWidget(self.cameraInput)
        self.open_camera_button = QtWidgets.QPushButton(self.layoutWidget)
        self.open_camera_button.setObjectName("open_camera_button")
        self.verticalLayout.addWidget(self.open_camera_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_users_button.setText(_translate("MainWindow", "Get all users"))
        self.add_user_button.setText(_translate("MainWindow", "Add user"))
        self.delete_user_button.setText(_translate("MainWindow", "Delete user"))
        self.add_image_button.setText(_translate("MainWindow", "Add image"))
        self.delete_image_button.setText(_translate("MainWindow", "Delete image"))
        self.add_camera_manager_button.setText(_translate("MainWindow", "Add camera manager"))
        self.delete_camera_manager_button.setText(_translate("MainWindow", "Delete camera manager"))
        self.delete_camera_info_button.setText(_translate("MainWindow", "Add camera info"))
        self.get_emotion_summary_button.setText(_translate("MainWindow", "Get emotion summary"))
        self.get_tracking_data_button.setText(_translate("MainWindow", "Add camera info"))
        self.cameraInput.setPlaceholderText(_translate("MainWindow", "Nhập ID Camera", "0"))
        self.open_camera_button.setText(_translate("MainWindow", "Open Camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
